### ISSUE TITLE
Poggit Release v2.1.2

### ISSUE THREAD

**Issue by JaxkDev** [DuoIncure/ComplexUpgradeUI#13]
Due to a poggit bug v2.1.2 (dev build 18) will not work for anyone due to incorrectly injected virions, please re-release v2.1.2 under a newer dev build where the bug no longer exists.

**Comment by DuoIncure** [comment]
Fixed as of https://github.com/ComplexityEU/ComplexUpgradeUI/commit/b78fdb3c83d21e755e026c0e0cc79a3813f1b74d

[Poggit Release](https://poggit.pmmp.io/p/ComplexUpgradeUI/2.1.3)
