### ISSUE TITLE
PM 5.4.0 - Fortune enchantment added

### ISSUE THREAD

**Issue by n00bslayr94** [DuoIncure/ComplexUpgradeUI#16]
[Thu_Aug_3-07.20.30-UTC_2023.log](https://github.com/ComplexityEU/ComplexUpgradeUI/files/12248026/Thu_Aug_3-07.20.30-UTC_2023.log)

```
PocketMine-MP Crash Dump Thu Aug 3 07:20:30 UTC 2023

PocketMine-MP version: 5.4.0 [Protocol 594]
Git commit: 01664d2e81eadb65a076fb665ba7c67cbd8e90a9
PHP version: 8.1.21
OS: Linux, linux

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: ComplexUpgradeUI

Thread: Main
Error: Alias "fortune" is already registered
File: pmsrc/src/utils/StringToTParser
Line: 51
Type: InvalidArgumentException
```

Updated to PM 5.4.0 - get error. Crashdump attached.

Changelogs for PM 5.4.0 show fortune enchantment has been implemented.

**Comment by DuoIncure** [comment]
For now, please use this [dev build](https://poggit.pmmp.io/r/217306/ComplexUpgradeUI_dev-28.phar) until a new release is published.

**Comment by n00bslayr94** [comment]
Thank you!
